/**:
  ros__parameters:
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    obstacles:
      x: [-1.4, 0.7, 0.5, 1.2, -1.7]
      y: [-1.7, -1.3, 0.8, -1.4, .9]
      r: 0.038
    arena_x_length: 7.0
    arena_y_length: 7.0
    basic_sensor_variance: 0.01
    lidar_variance: 0.01
    slip_fraction: 0.02
    input_noise: 0.01
    basic_sensor_range: 1.0